// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SNMPManager.Core.Entities;
using System;

namespace SNMPManager.Core.Migrations
{
    [DbContext(typeof(SnmpManagerContext))]
    partial class SnmpManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SNMPManager.Core.Entities.Sonar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IpAddress");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Mib");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Sonars");
                });
#pragma warning restore 612, 618
        }
    }
}
